spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: demo-library
server:
  port: 8088
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: test123
#    key-store-type: PKCS12
#    key-alias: selfsigned

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

  security:
    enabled: false
